#!/bin/zsh
# Regenerates the built-in string snapshot (app.md T-10) from a running server.
#
#   scripts/update-strings.sh http://127.0.0.1:5000
#
# Fetches GET /locales, then GET /i18n/{lang} for each language, and writes them
# verbatim into Sources/SplouchCore/Strings/BuiltInStrings.generated.swift. The
# app never edits these by hand: the server's shared/locales/ is the source, this
# is a compiled floor for a first launch, an offline start or a cleared cache.
set -euo pipefail
BASE=${1:?usage: update-strings.sh <server base url>}
ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT=$ROOT/Sources/SplouchCore/Strings/BuiltInStrings.generated.swift
BASE=${BASE%/}

codes=$(curl -sfS "$BASE/locales" | python3 -c 'import json,sys; print(" ".join(sorted(e["code"] for e in json.load(sys.stdin))))')
[[ -n "$codes" ]] || { echo "no locales from $BASE" >&2; exit 1 }

{
    echo "// Generated by scripts/update-strings.sh from $BASE on $(date -u +%Y-%m-%dT%H:%MZ)."
    echo "// Do not edit: the server's shared/locales/ is the source (app.md T-10)."
    echo ""
    echo "extension BuiltInStrings {"
    echo "    static let generated: [String: String] = ["
    for code in ${=codes}; do
        body=$(curl -sfS "$BASE/i18n/$code" | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin), ensure_ascii=False, sort_keys=True, separators=(",", ":")))')
        echo "        \"$code\": #\"\"\""
        echo "$body"
        echo "\"\"\"#,"
    done
    echo "    ]"
    echo "}"
} > "$OUT"
echo "wrote $OUT for: $codes"
